name: FallenKingdom
version: ${project.version}
main: fr.devsylone.fallenkingdom.FkMock

commands:
  fk:
    usage: <command> help

permissions:
  fallenkingdom.admin:
    description: Permet d'éditer les paramètres du Fallen Kingdom
    default: op
  fallenkingdom.player:
    description: Permet d'afficher les règles et les équipes
    default: true